### ISSUE TITLE
Connman don't like -

### ISSUE THREAD

**Issue by xorob0** [march-linux/connman_dmenu#4]
Hello,
I am adding this issue to inform you of a problem I had with connman. When I was trying to connect to my university network (SSID : "ULg-Secure"), using the dmenu interface, I had a little problem, it told me "invalid argument". When I looked in the /var/lib/connman directory I found ULg_Secure-... (note the _ instead of the -) when I took a look inside I found "Name : ULg_Secure", and here is the problem. I just changed the _ to a - and it worked back again. I do not know if this is a bug inside connman itself or a bug from the dmenu interface.

Thanks a lot for your great work !

PS : I also have an other problem, I need to start connmanctl, type agent on, connect to a wifi, type the password, then type it again int the connmanctl command line in order to connect to wpa. Should I start an other issue ?

**Comment by taylorchu** [comment]
For your second issue, I don't understand "connect to wpa" because wpa is a local daemon. connman_dmenu should get you on any wifi.
